name: poc
description: "KDDockWidgets Flutter multi-window POC."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  kdab_dart_analysis: ^0.0.2

flutter:
  uses-material-design: true
